"""Edit image and post

Revision ID: f17ccf190808
Revises: cb64fac66abf
Create Date: 2024-05-26 21:40:50.756247

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f17ccf190808'
down_revision = 'cb64fac66abf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('images', schema=None) as batch_op:
        batch_op.drop_column('object_id')
        batch_op.drop_column('object_type')

    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('background_image_id', sa.String(length=100), nullable=False))
        batch_op.create_foreign_key(batch_op.f('fk_posts_background_image_id_images'), 'images', ['background_image_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_posts_background_image_id_images'), type_='foreignkey')
        batch_op.drop_column('background_image_id')

    with op.batch_alter_table('images', schema=None) as batch_op:
        batch_op.add_column(sa.Column('object_type', mysql.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('object_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
