"""Edit post again

Revision ID: fe640de1398a
Revises: f17ccf190808
Create Date: 2024-05-26 21:44:12.994070

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'fe640de1398a'
down_revision = 'f17ccf190808'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.alter_column('title',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.Text(),
               existing_nullable=False)
        batch_op.drop_column('body')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('body', mysql.TEXT(), nullable=False))
        batch_op.alter_column('title',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=False)

    # ### end Alembic commands ###
